# Generated by Django 3.2.9 on 2021-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20211206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
